import type { EditorThemeClasses } from 'lexical';
import type { EditorThemeClassName } from 'lexical/LexicalEditor';
import styles from './editor-theme.module.scss';
import './theme.scss';

const theme: EditorThemeClasses = {
  blockCursor: styles['EditorTheme__blockCursor'],
  characterLimit: styles['EditorTheme__characterLimit'],
  code: styles['EditorTheme__code'],
  codeHighlight: {
    atrule: styles['EditorTheme__tokenAttr'],
    attr: styles['EditorTheme__tokenAttr'],
    boolean: styles['EditorTheme__tokenProperty'],
    builtin: styles['EditorTheme__tokenSelector'],
    cdata: styles['EditorTheme__tokenComment'],
    char: styles['EditorTheme__tokenSelector'],
    class: styles['EditorTheme__tokenFunction'],
    'class-name': styles['EditorTheme__tokenFunction'],
    comment: styles['EditorTheme__tokenComment'],
    constant: styles['EditorTheme__tokenProperty'],
    deleted: styles['EditorTheme__tokenProperty'],
    doctype: styles['EditorTheme__tokenComment'],
    entity: styles['EditorTheme__tokenOperator'],
    function: styles['EditorTheme__tokenFunction'],
    important: styles['EditorTheme__tokenVariable'],
    inserted: styles['EditorTheme__tokenSelector'],
    keyword: styles['EditorTheme__tokenAttr'],
    namespace: styles['EditorTheme__tokenVariable'],
    number: styles['EditorTheme__tokenProperty'],
    operator: styles['EditorTheme__tokenOperator'],
    prolog: styles['EditorTheme__tokenComment'],
    property: styles['EditorTheme__tokenProperty'],
    punctuation: styles['EditorTheme__tokenPunctuation'],
    regex: styles['EditorTheme__tokenVariable'],
    selector: styles['EditorTheme__tokenSelector'],
    string: styles['EditorTheme__tokenSelector'],
    symbol: styles['EditorTheme__tokenProperty'],
    tag: styles['EditorTheme__tokenProperty'],
    url: styles['EditorTheme__tokenOperator'],
    variable: styles['EditorTheme__tokenVariable'],
  } as Record<string, EditorThemeClassName>,
  embedBlock: {
    base: styles['EditorTheme__embedBlock'],
    focus: styles['EditorTheme__embedBlockFocus'],
  },
  hashtag: styles['EditorTheme__hashtag'],
  heading: {
    h1: styles['EditorTheme__h1'],
    h2: styles['EditorTheme__h2'],
    h3: styles['EditorTheme__h3'],
    h4: styles['EditorTheme__h4'],
    h5: styles['EditorTheme__h5'],
    h6: styles['EditorTheme__h6'],
  },
  indent: styles['EditorTheme__indent'],
  layoutContainer: styles['EditorTheme__layoutContainer'],
  layoutItem: styles['EditorTheme__layoutItem'],
  link: styles['EditorTheme__link'],
  list: {
    listitem: styles['EditorTheme__listItem'],
    listitemChecked: styles['EditorTheme__listItemChecked'],
    listitemUnchecked: styles['EditorTheme__listItemUnchecked'],
    nested: {
      listitem: styles['EditorTheme__nestedListItem'],
    },
    olDepth: [
      'EditorTheme__ol1',
      'EditorTheme__ol2',
      'EditorTheme__ol3',
      'EditorTheme__ol4',
      'EditorTheme__ol5',
    ],
    ul: styles['EditorTheme__ul'],
  },
  ltr: styles['EditorTheme__ltr'],
  mark: styles['EditorTheme__mark'],
  markOverlap: styles['EditorTheme__markOverlap'],
  paragraph: styles['EditorTheme__paragraph'],
  quote: styles['EditorTheme__quote'],
  rtl: styles['EditorTheme__rtl'],
  table: styles['EditorTheme__table'],
  tableAddColumns: styles['EditorTheme__tableAddColumns'],
  tableAddRows: styles['EditorTheme__tableAddRows'],
  tableCell: styles['EditorTheme__tableCell'],
  tableCellActionButton: styles['EditorTheme__tableCellActionButton'],
  tableCellActionButtonContainer: 'EditorTheme__tableCellActionButtonContainer',
  tableCellEditing: styles['EditorTheme__tableCellEditing'],
  tableCellHeader: styles['EditorTheme__tableCellHeader'],
  tableCellPrimarySelected: styles['EditorTheme__tableCellPrimarySelected'],
  tableCellResizer: styles['EditorTheme__tableCellResizer'],
  tableCellSelected: styles['EditorTheme__tableCellSelected'],
  tableCellSortedIndicator: styles['EditorTheme__tableCellSortedIndicator'],
  tableResizeRuler: styles['EditorTheme__tableCellResizeRuler'],
  tableSelected: styles['EditorTheme__tableSelected'],
  tableSelection: styles['EditorTheme__tableSelection'],
  text: {
    bold: styles['EditorTheme__textBold'],
    code: styles['EditorTheme__textCode'],
    italic: styles['EditorTheme__textItalic'],
    strikethrough: styles['EditorTheme__textStrikethrough'],
    subscript: styles['EditorTheme__textSubscript'],
    superscript: styles['EditorTheme__textSuperscript'],
    underline: styles['EditorTheme__textUnderline'],
    underlineStrikethrough: styles['EditorTheme__textUnderlineStrikethrough'],
  },
  image: 'editor-image',
  inlineImage: 'inline-editor-image',
};

export default theme;
